### ISSUE TITLE
Service not printing on windows 10

### ISSUE THREAD

**Issue by SaadYasir** [huysentruitw/print-it#12]
when running it as service on windows 10. it doesn't print anything. but when debugging it in visual studio it works well

**Comment by huysentruitw** [comment]
Does it work when you run it from the console (start the exe with the flag `--console`) ?

If it runs as a service, the user the service runs under must have printers installed (Windows links printers to users IIRC). It can help to use a service account instead of `Network Service` or `Local System`.

**Comment by Vasanthvivi** [comment]
> Does it work when you run it from the console (start the exe with the flag `--console`) ?
> 
> If it runs as a service, the user the service runs under must have printers installed (Windows links printers to users IIRC). It can help to use a service account instead of `Network Service` or `Local System`.

Yes it works when running as console application but it is not working while running as a service ,,, according to the microsoft docs the PrintDocument is based on WinForms and i think windows service dont have the rights to print documents

**Comment by yiwan74** [comment]
Is any solution found about this issue?
Printing from service is not possible. Any workaround for this problem?

> 
> Yes it works when running as console application but it is not working while running as a service ,,, according to the microsoft docs the PrintDocument is based on WinForms and i think windows service dont have the rights to print documents

**Comment by SaadYasir** [comment]
I was able to print using service.
I will contribute the code for this fix

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yiwan74** [comment]
Yes. You are right. It can print from service.
I was trying to print from service on printer that was redirected through remote desktop.
In that case it prints only when started with Visual Studio.
But when I used local network printer it prints well from service too.
