### ISSUE TITLE
Add the spool name

### ISSUE THREAD

**Issue by yandora8** [huysentruitw/print-it#16]
Great software!
Do you plan to add arguments (spool name)?
All spools from this software are "document".
I would like to set the filename as the spool name.
thank you.

**Comment by huysentruitw** [comment]
I'm open a PR if you want to add an additional (and optional) parameter `UseFileNameAsSpoolName`. If a setting like this would solve the request you have, of course.

**Comment by yandora8** [comment]
Thanks you.

**Comment by huysentruitw** [comment]
I'm adding the flag `UseFileNameAsDocumentName` as I believe you want to set the document name instead of spool name, right?

**Comment by yandora8** [comment]
OK. Thank you.

**Comment by EliezerBeniz** [comment]
Hello, is it possible to use this service to make a local print but through an external api?
