### ISSUE TITLE
Scaling/Zooming Problem

### ISSUE THREAD

**Issue by Accout-Personal** [huysentruitw/print-it#21]
The api doenst give a setting on scaling/zooming when printing. It seems it uses the default option which it could "adapt" the printing content to the page. And sometime is not intended result.

**Comment by brendonparker** [comment]
I ran into this problem in another (paid) pdf library: Winnovative.

If the default printer was set to a 4x6 label printer, for example, when printing to a 8.5x11 document printer, it was picking up the default 4x6 label printer and appeared to be using it's print settings, coming out as a 4x6, but on the 8.5x11 page. At least this is what I _think_ was happening.

I just started searching for an alternative. Curious, what would need to change in this code make this scenario not work, i.e. not "use the default" printer settings.
