### ISSUE TITLE
cors problem

### ISSUE THREAD

**Issue by pargent70** [huysentruitw/print-it#29]
I tried to call 'http://localhost:7000/print/from-pdf' with javascript/ajax from my localhost:80

but I obtain  this :
Access to XMLHttpRequest at 'http://localhost:7000/print/from-pdf' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

can ( and how ) I fix this ? 

thanks
kind regards

**Comment by huysentruitw** [comment]
These endpoints are meant for server-to-server communication and should not be called by a front-end directly. Exposing this to the public or intranet without proper security can lead to abuse.
