### ISSUE TITLE
Web server not responding even after following read me instructions

### ISSUE THREAD

**Issue by Pulkit-Taneja** [huysentruitw/print-it#32]
![IMG_6997](https://github.com/huysentruitw/print-it/assets/41661434/63ce7a39-a222-4e0b-aee0-0e7e3eed9d7a)
![IMG_6998](https://github.com/huysentruitw/print-it/assets/41661434/70eeaa45-a4f9-400f-88af-f1f0b4db1432)
Please help

**Comment by Pulkit-Taneja** [comment]
@huysentruitw 
What could the the problem here ?

**Comment by huysentruitw** [comment]
Can you try adding `/printers/list` to the URL? I don't think anything is served from the root path (/), so 404 is expected there.

**Comment by Pulkit-Taneja** [comment]
Hey got it my bad. Also I only have local printers which works over a USB port, it does show up on the printer list page, will that work or only network printers are supported.
The model of my printer is HP laserjet 1020.
Thanks
