### ISSUE TITLE
Can't get the web server to respond

### ISSUE THREAD

**Issue by dgwaldo** [huysentruitw/print-it#8]
Trying to get this setup, and I can't seem to get the server to respond. At first I thought it was an issue with the service registration or something, so deleted and registered it using NSSM.  That also didn't work. Pulled the source and fired up the project and it says it's listening on the correct host:port combo, but no luck. I've tried a variety of ports, checked everything simple I can think of. Anyone else running into this?

**Comment by huysentruitw** [comment]
Are you trying to connect from a different machine on the network, or on the machine where the service is running?

**Comment by dgwaldo** [comment]
On the machine where the service is running. I had a work mate give it a go and he had the same result. VS2019 latest version of Windows 10.

**Comment by huysentruitw** [comment]
I have added some usage instructions to the README file [here](https://github.com/huysentruitw/print-it/blob/develop/README.md#usage-instructions).

I've tested this locally and the service starts as expected. Can you undo any previous service registration and try the instructions from the README?

**Comment by dgwaldo** [comment]
That was helpful thanks
